# Generated by Django 2.2.3 on 2019-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
