# Generated by Django 2.2.3 on 2019-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_remove_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='votes_qestion1',
            field=models.IntegerField(default=0),
        ),
    ]
