# Generated by Django 2.2.3 on 2019-08-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20190802_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
