# Generated by Django 2.2.3 on 2019-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes_qestion2',
            field=models.IntegerField(default=0),
        ),
    ]
